name: Format Python Code with Black using Node.js 20

# This workflow will run on push and pull request events
on: [push, pull_request]

jobs:
  format-code:
    # Define the environment to run on Ubuntu
    runs-on: ubuntu-latest

    steps:
    # Step 1: Set up Node.js 20 environment
    - name: Set up Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20' # Specify Node.js version 20 explicitly

    # Step 2: Check out the code from the repository
    - name: Check out code
      uses: actions/checkout@v3 # This version is already compatible with Node.js 20

    # Step 3: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4 # This version is already compatible with Node.js 20
      with:
        python-version: '3.x'

    # Step 4: Install Python dependencies
    - name: Install Black
      run: |
        python -m pip install --upgrade pip
        pip install black

    # Step 5: Run Black code formatter
    - name: Run Black
      run: |
        black . --check

    # Optional Step 6: Run any Node.js based tasks (if needed)
    # - name: Run Node.js commands
    #   run: |
    #     npm install
    #     npm run some-task
