name: Format Python Code with Black using Node.js 16

# This workflow will run on push and pull request events
on: [push, pull_request]

jobs:
  format-code:
    # Define the environment to run on Ubuntu
    runs-on: ubuntu-latest

    steps:
    # Step 1: Set up Node.js 16 environment (optional if you want Node.js 16)
    - name: Set up Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Step 2: Check out the code from the repository
    - name: Check out code
      uses: actions/checkout@v3 # Updated to version 3 to ensure Node.js 16 compatibility

    # Step 3: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4 # Updated to version 4 to ensure Node.js 16 compatibility
      with:
        python-version: '3.x'

    # Step 4: Install Python dependencies
    - name: Install Black
      run: |
        python -m pip install --upgrade pip
        pip install black

    # Step 5: Run Black code formatter
    - name: Run Black
      run: |
        black . --check
